##  4 Python Operators

### 4.1.  Basic Operators : <font color=blue>+, -, \*, /, %, /, \*\*, +=, -=</font> ###

In [1]:
# basic operators
a, b=2,7
print ("a+b = ", a+b)             # addition/concatenation
print ("a-b = ", a-b )            # subtraction
print ("a*b = ", a*b )            # multiplication

a+b =  9
a-b =  -5
a*b =  14


In [2]:
# division. Notice that a,b are integers 
# in python2, b/a is also an integer
# in python3, b/a is a float
print ("b/a = ", b/a )    

b/a =  3.5


### 4.2. Comparison Operators: <font color=blue>==, !=, >, <, >=, <=, is, not is, in, not in </font> ###
- Boolean data type

In [3]:
#  comparison operators  -- value comparison
a, b = 2,7
print ("a==b ?", a==b)          # equal
print ("a!=b ?", a!=b )         # not Equal
print ("a>b ?",a>b)             # greater than
print ("a<b ?",a<b )            # less than

a==b ? False
a!=b ? True
a>b ? False
a<b ? True


In [4]:
# comparison operators -- identity operator
a, b =2,7

# test if both sides of the operator point to the **same object**
print ("a is 2 ?", a is 2)     
# test if both sides of the operator are not the same object
print ("a is not b ?",a is not b)    

a is 2 ? True
a is not b ? True


In [5]:
#  Question: identity operator "is" is equivalent to "=="?
#  Try the following 
x = [1,2,3]
y = [1,2,3]
print("x==y? ", x==y)
print("x is y? ", x is y)
# Conclusion: 
# "is": object equality, "==": value equality
# for small integers, "is" perhaps is equivalent to "=="
# for composite data types, they are different
# for details, check discussion: https://stackoverflow.com/questions/132988/is-there-a-difference-between-and-is-in-python

x==y?  True
x is y?  False


In [6]:
# comparison operators -- membership operator
a, b, c=2, 7, [1,2,3]
a=2
b=7
# test if a is in list c
print ("a in c ? ",a in c) 
# test if b is not in list c
print ("b not in c ? ",b not in c)  

a in c ?  True
b not in c ?  True


### 4.3. Logical Operators :<font color=blue> and, or, not </font> ###

In [7]:
# Exercise: logical operators
a, b, c=2,7, [1,2,3]
# both conditions are true
print ("(a>b) and (a in c) ?",(a>b) and (a in c))     
# either condition is true
print ("(a>b) or (a in c) ?",(a>b) or (a in c))
# reverse the condition
print ("not (a>b) ?",not (a>b) )                    

(a>b) and (a in c) ? False
(a>b) or (a in c) ? True
not (a>b) ? True


![](http://sixthresearcher.com/wp-content/uploads/2016/12/Python3_reference_cheat_sheet_front.png)

# Condition: if...else...

In [8]:
x = 100
if x>=200:
    print ("the value of x >= 200")
else:
    print ("the value of x < 200")

the value of x < 200


In [9]:
x = 300
if x>=200:
    print ("the value of x >= 200")
elif x>=50:
    print ("the value of x >= 50 and <200")
else:
    print ("the value of x < 50")

the value of x >= 200


<img src="https://cdn.programiz.com/sites/tutorial2program/files/Python_if_elif_else_statement.jpg" width = "400" height="300">

# Define your own Function

In [10]:
def areaofcircle(r):
    area = 3.14*r**2
    return area

In [11]:
areaofcircle(2)

12.56

# package

`pip install `: package maintenance system for python

In [12]:
import math

In [13]:
math.pi

3.141592653589793

In [14]:
from math import pi

In [15]:
pi

3.141592653589793

In [16]:
import numpy as np

## list review
- collection of values
- hold different types
- change, add and remove

In [17]:
height = [1.75, 1.79, 1.85, 1.83]
weight = [65.4, 59.2, 88.5, 78.3]

$$\mathrm{BMI} = \frac{\mathrm{weight (kg)}}{\mathrm{height (m)}^2}$$

In [18]:
bmi = weight/height**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

# NumPy
- Numeric Python
- A numpy **array** is a grid of values, **all of the same type** (different from list!). 
    - The **shape** of an array is a tuple of integers giving the size of the array along each dimension
    - Numpy arrays can be initialized from nested Python lists, and access elements using square brackets

In [19]:
a = np.array([1, 2, 3])  
a

array([1, 2, 3])

In [20]:
type(a)

numpy.ndarray

**ndarray = n-deminsonal array**

In [21]:
b = np.array([[1,2,3],[4,5,6]])   
b

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
b.shape

(2, 3)

In [23]:
#True is converted to 1, False is converted to 0.
np.array([True, 1, 2])

array([1, 1, 2])

In [24]:
np.array([1.0, "is", True])

array(['1.0', 'is', 'True'], dtype='<U32')

## 1. Array math
- Basic mathematical functions operate **elementwise** on arrays, and are available both as operator overloads and as functions in the numpy module

In [25]:
np_height = np.array([1.75, 1.79, 1.85, 1.83])
np_weight = np.array([65.4, 59.2, 88.5, 78.3])

In [26]:
bmi = np_weight/np_height**2

In [27]:
bmi

array([21.35510204, 18.47632721, 25.85829072, 23.38081161])

In [28]:
#Addition
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
# Elementwise sum; both produce the array
print (x + y)
print (np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [29]:
# Subtraction; Elementwise difference; both produce the array
print (x - y)
print (np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [30]:
x*2

array([[2, 4],
       [6, 8]])

In [31]:
x+2

array([[3, 4],
       [5, 6]])

In [32]:
py_list = [1,2,3]
py_list + py_list

[1, 2, 3, 1, 2, 3]

In [33]:
np_list = np.array([1,2,3])
np_list + np_list

array([2, 4, 6])

|function| meaning   |
|-------|-------------------|
|a.sum()|	Array-wise sum  |
|a.min()|	Array-wise minimum value  |
|a.max(axis=0)|	Maximum value of an array row  |
|a.cumsum(axis=1)|	Cumulative sum of the elements  |
|a.mean()|	Mean | 
|a.median()|	Median|  
|a.corrcoef()|	Correlation coefficient | 
|np.multiply()|Multiplication|
|np.divide()|Division|
|np.std(a)|	Standard deviation  |
|np.dot(a,b)|vector/matrix product|

## 2. Array Slicing
 - **Similar to Python lists, numpy arrays can be sliced**. 
 - Since arrays may be multidimensional, you must **specify a slice for each dimension of the array**

In [34]:
a = np.array([1, 2, 3])  
a[0]

1

In [35]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [36]:
b[0]

array([1, 2, 3, 4])

In [37]:
b[0][0]

1

In [38]:
b[0,0]

1

In [39]:
column_1=b[:, 0]  
column_1

array([1, 5, 9])

In [40]:
b[:2, 1:3]#1st, 2nd rows and 2nd, 3rd columns

array([[2, 3],
       [6, 7]])

In [41]:
c = np.array([[ 89,  83,  49,  77,  49,  79,   0,  47,  44,  18,  87,  82,  69,
         32,   8],
       [ 85,  66,  16,  34,  27,  56,  42,  20,  69,  92,  93,  50,  75,
         21,  96],
       [ 77,  35,  39,  32,  93,  28,  87,  32,  65,  10,   8,  10,  54,
         98,  31]])
#1. print out the shape of "c"
c.shape
#2. Print out the 3rd row of "c"
c[2]
#3. print out the element an the 2nd row and 4th column
c[1,3]
#4. print out the last two rows and last two columns?
c[-2:, -2:]

(3, 15)

array([77, 35, 39, 32, 93, 28, 87, 32, 65, 10,  8, 10, 54, 98, 31])

34

array([[21, 96],
       [98, 31]])

## 3. Boolean array indexing(Selection by conditions)

- Boolean array indexing lets you pick out arbitrary elements of an array. 
- Frequently this type of indexing is used to select elements of an array that satisfy some conditions. 

In [42]:
a = np.array([[1,2], [3, 4], [5, 6]])
# Find the elements of "a" that are bigger than 2;
# this returns a numpy array of Booleans of the same
# shape as a, where value tells
# whether that element of a is > 2

bool_idx = (a > 2)  
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [43]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

[3 4 5 6]


In [44]:
bmi

array([21.35510204, 18.47632721, 25.85829072, 23.38081161])

In [45]:
bmi>23

array([False, False,  True,  True])

In [46]:
bmi[bmi>23]

array([25.85829072, 23.38081161])

** Assignment 1**

In [47]:
height = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73, 74, 74, 72, 75, 74, 74, 77, 75, 73, 72, 71, 74, 77, 75, 75, 75, 78, 78, 74, 76, 78, 76, 70, 72, 80, 74, 74, 71, 70, 72, 71, 74, 71, 72, 71, 74, 69, 76, 75, 75, 76, 73, 76, 73, 77, 73, 72, 72, 77, 77, 71, 74, 74, 73, 78, 75, 73, 70, 74, 72, 73, 73, 75, 75, 74, 76, 73, 74, 75, 75, 72, 73, 73, 72, 74, 78, 76, 73, 74, 75, 70, 75, 71, 72, 78, 75, 73, 73, 71, 75, 77, 72, 69, 73, 74, 72, 70, 75, 70, 72, 72, 74, 73, 74, 76, 75, 80, 72, 75, 73, 74, 74, 73, 75, 75, 71, 73, 75, 74, 74, 72, 74, 74, 74, 73, 76, 75, 72, 73, 73, 73, 72, 72, 72, 72, 71, 75, 75, 74, 73, 75, 79, 74, 76, 73, 74, 74, 72, 74, 74, 75, 78, 74, 74, 74, 77, 70, 73, 74, 73, 71, 75, 71, 72, 77, 74, 70, 77, 73, 72, 76, 71, 76, 78, 75, 73, 78, 74, 79, 75, 76, 72, 75, 75, 70, 72, 70, 74, 71, 76, 73, 76, 71, 69, 72, 72, 69, 73, 69, 73, 74, 74, 72, 71, 72, 72, 76, 76, 76, 74, 76, 75, 71, 72, 71, 73, 75, 76, 75, 71, 75, 74, 72, 73, 73, 73, 73, 76, 72, 76, 73, 73, 73, 75, 75, 77, 73, 72, 75, 70, 74, 72, 80, 71, 71, 74, 74, 73, 75, 76, 73, 77, 72, 73, 77, 76, 71, 75, 73, 74, 77, 71, 72, 73, 69, 73, 70, 74, 76, 73, 73, 75, 73, 79, 74, 73, 74, 77, 75, 74, 73, 77, 73, 77, 74, 74, 73, 77, 74, 77, 75, 77, 75, 71, 74, 70, 79, 72, 72, 70, 74, 74, 72, 73, 72, 74, 74, 76, 82, 74, 74, 70, 73, 73, 74, 77, 72, 76, 73, 73, 72, 74, 74, 71, 72, 75, 74, 74, 77, 70, 71, 73, 76, 71, 75, 74, 72, 76, 79, 76, 73, 76, 78, 75, 76, 72, 72, 73, 73, 75, 71, 76, 70, 75, 74, 75, 73, 71, 71, 72, 73, 73, 72, 69, 73, 78, 71, 73, 75, 76, 70, 74, 77, 75, 79, 72, 77, 73, 75, 75, 75, 73, 73, 76, 77, 75, 70, 71, 71, 75, 74, 69, 70, 75, 72, 75, 73, 72, 72, 72, 76, 75, 74, 69, 73, 72, 72, 75, 77, 76, 80, 77, 76, 79, 71, 75, 73, 76, 77, 73, 76, 70, 75, 73, 75, 70, 69, 71, 72, 72, 73, 70, 70, 73, 76, 75, 72, 73, 79, 71, 72, 74, 74, 74, 72, 76, 76, 72, 72, 71, 72, 72, 70, 77, 74, 72, 76, 71, 76, 71, 73, 70, 73, 73, 72, 71, 71, 71, 72, 72, 74, 74, 74, 71, 72, 75, 72, 71, 72, 72, 72, 72, 74, 74, 77, 75, 73, 75, 73, 76, 72, 77, 75, 72, 71, 71, 75, 72, 73, 73, 71, 70, 75, 71, 76, 73, 68, 71, 72, 74, 77, 72, 76, 78, 81, 72, 73, 76, 72, 72, 74, 76, 73, 76, 75, 70, 71, 74, 72, 73, 76, 76, 73, 71, 68, 71, 71, 74, 77, 69, 72, 76, 75, 76, 75, 76, 72, 74, 76, 74, 72, 75, 78, 77, 70, 72, 79, 74, 71, 68, 77, 75, 71, 72, 70, 72, 72, 73, 72, 74, 72, 72, 75, 72, 73, 74, 72, 78, 75, 72, 74, 75, 75, 76, 74, 74, 73, 74, 71, 74, 75, 76, 74, 76, 76, 73, 75, 75, 74, 68, 72, 75, 71, 70, 72, 73, 72, 75, 74, 70, 76, 71, 82, 72, 73, 74, 71, 75, 77, 72, 74, 72, 73, 78, 77, 73, 73, 73, 73, 73, 76, 75, 70, 73, 72, 73, 75, 74, 73, 73, 76, 73, 75, 70, 77, 72, 77, 74, 75, 75, 75, 75, 72, 74, 71, 76, 71, 75, 76, 83, 75, 74, 76, 72, 72, 75, 75, 72, 77, 73, 72, 70, 74, 72, 74, 72, 71, 70, 71, 76, 74, 76, 74, 74, 74, 75, 75, 71, 71, 74, 77, 71, 74, 75, 77, 76, 74, 76, 72, 71, 72, 75, 73, 68, 72, 69, 73, 73, 75, 70, 70, 74, 75, 74, 74, 73, 74, 75, 77, 73, 74, 76, 74, 75, 73, 76, 78, 75, 73, 77, 74, 72, 74, 72, 71, 73, 75, 73, 67, 67, 76, 74, 73, 70, 75, 70, 72, 77, 79, 78, 74, 75, 75, 78, 76, 75, 69, 75, 72, 75, 73, 74, 75, 75, 73]
weight = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230, 195, 180, 192, 225, 203, 195, 182, 188, 200, 180, 200, 200, 245, 240, 215, 185, 175, 199, 200, 215, 200, 205, 206, 186, 188, 220, 210, 195, 200, 200, 212, 224, 210, 205, 220, 195, 200, 260, 228, 270, 200, 210, 190, 220, 180, 205, 210, 220, 211, 200, 180, 190, 170, 230, 155, 185, 185, 200, 225, 225, 220, 160, 205, 235, 250, 210, 190, 160, 200, 205, 222, 195, 205, 220, 220, 170, 185, 195, 220, 230, 180, 220, 180, 180, 170, 210, 215, 200, 213, 180, 192, 235, 185, 235, 210, 222, 210, 230, 220, 180, 190, 200, 210, 194, 180, 190, 240, 200, 198, 200, 195, 210, 220, 190, 210, 225, 180, 185, 170, 185, 185, 180, 178, 175, 200, 204, 211, 190, 210, 190, 190, 185, 290, 175, 185, 200, 220, 170, 220, 190, 220, 205, 200, 250, 225, 215, 210, 215, 195, 200, 194, 220, 180, 180, 170, 195, 180, 170, 206, 205, 200, 225, 201, 225, 233, 180, 225, 180, 220, 180, 237, 215, 190, 235, 190, 180, 165, 195, 200, 190, 190, 185, 185, 205, 190, 205, 206, 220, 208, 170, 195, 210, 190, 211, 230, 170, 185, 185, 241, 225, 210, 175, 230, 200, 215, 198, 226, 278, 215, 230, 240, 184, 219, 170, 218, 190, 225, 220, 176, 190, 197, 204, 167, 180, 195, 220, 215, 185, 190, 205, 205, 200, 210, 215, 200, 205, 211, 190, 208, 200, 210, 232, 230, 210, 220, 210, 202, 212, 225, 170, 190, 200, 237, 220, 170, 193, 190, 150, 220, 200, 190, 185, 185, 200, 172, 220, 225, 190, 195, 219, 190, 197, 200, 195, 210, 177, 220, 235, 180, 195, 195, 190, 230, 190, 200, 190, 190, 200, 200, 184, 200, 180, 219, 187, 200, 220, 205, 190, 170, 160, 215, 175, 205, 200, 214, 200, 190, 180, 205, 220, 190, 215, 235, 191, 200, 181, 200, 210, 240, 185, 165, 190, 185, 175, 155, 210, 170, 175, 220, 210, 205, 200, 205, 195, 240, 150, 200, 215, 202, 200, 190, 205, 190, 160, 215, 185, 200, 190, 210, 185, 220, 190, 202, 205, 220, 175, 160, 190, 200, 229, 206, 220, 180, 195, 175, 188, 230, 190, 200, 190, 219, 235, 180, 180, 180, 200, 234, 185, 220, 223, 200, 210, 200, 210, 190, 177, 227, 180, 195, 199, 175, 185, 240, 210, 180, 194, 225, 180, 205, 193, 230, 230, 220, 200, 249, 190, 208, 245, 250, 160, 192, 220, 170, 197, 155, 190, 200, 220, 210, 228, 190, 160, 184, 180, 180, 200, 176, 160, 222, 211, 195, 200, 175, 206, 240, 185, 260, 185, 221, 205, 200, 170, 201, 205, 185, 205, 245, 220, 210, 220, 185, 175, 170, 180, 200, 210, 175, 220, 206, 180, 210, 195, 200, 200, 164, 180, 220, 195, 205, 170, 240, 210, 195, 200, 205, 192, 190, 170, 240, 200, 205, 175, 250, 220, 224, 210, 195, 180, 245, 175, 180, 215, 175, 180, 195, 230, 230, 205, 215, 195, 180, 205, 180, 190, 180, 190, 190, 220, 210, 255, 190, 230, 200, 205, 210, 225, 215, 220, 205, 200, 220, 197, 225, 187, 245, 185, 185, 175, 200, 180, 188, 225, 200, 210, 245, 213, 231, 165, 228, 210, 250, 191, 190, 200, 215, 254, 232, 180, 215, 220, 180, 200, 170, 195, 210, 200, 220, 165, 180, 200, 200, 170, 224, 220, 180, 198, 240, 239, 185, 210, 220, 200, 195, 220, 230, 170, 220, 230, 165, 205, 192, 210, 205, 200, 210, 185, 195, 202, 205, 195, 180, 200, 185, 240, 185, 220, 205, 205, 180, 201, 190, 208, 240, 180, 230, 195, 215, 190, 195, 215, 215, 220, 220, 230, 195, 190, 195, 209, 204, 170, 185, 205, 175, 210, 190, 180, 180, 160, 235, 200, 210, 180, 190, 197, 203, 205, 170, 200, 250, 200, 220, 200, 190, 170, 190, 220, 215, 206, 215, 185, 235, 188, 230, 195, 168, 190, 160, 200, 200, 189, 180, 190, 200, 220, 187, 240, 190, 180, 185, 210, 220, 219, 190, 193, 175, 180, 215, 210, 200, 190, 185, 220, 170, 195, 205, 195, 210, 190, 190, 180, 220, 190, 186, 185, 190, 180, 190, 170, 210, 240, 220, 180, 210, 210, 195, 160, 180, 205, 200, 185, 245, 190, 210, 200, 200, 222, 215, 240, 170, 220, 156, 190, 202, 221, 200, 190, 210, 190, 200, 165, 190, 185, 230, 208, 209, 175, 180, 200, 205, 200, 250, 210, 230, 244, 202, 240, 200, 215, 177, 210, 170, 215, 217, 198, 200, 220, 170, 200, 230, 231, 183, 192, 167, 190, 180, 180, 215, 160, 205, 223, 175, 170, 190, 240, 175, 230, 223, 196, 167, 195, 190, 250, 190, 190, 190, 170, 160, 150, 225, 220, 209, 210, 176, 260, 195, 190, 184, 180, 195, 195, 219, 225, 212, 202, 185, 200, 209, 200, 195, 228, 210, 190, 212, 190, 218, 220, 190, 235, 210, 200, 188, 210, 235, 188, 215, 216, 220, 180, 185, 200, 210, 220, 185, 231, 210, 195, 200, 205, 200, 190, 250, 185, 180, 170, 180, 208, 235, 215, 244, 220, 185, 230, 190, 200, 180, 190, 196, 180, 230, 224, 160, 178, 205, 185, 210, 180, 190, 200, 257, 190, 220, 165, 205, 200, 208, 185, 215, 170, 235, 210, 170, 180, 170, 190, 150, 230, 203, 260, 246, 186, 210, 198, 210, 215, 180, 200, 245, 200, 192, 192, 200, 192, 205, 190, 186, 170, 197, 219, 200, 220, 207, 225, 207, 212, 225, 170, 190, 210, 230, 210, 200, 238, 234, 222, 200, 190, 170, 220, 223, 210, 215, 196, 175, 175, 189, 205, 210, 180, 180, 197, 220, 228, 190, 204, 165, 216, 220, 208, 210, 215, 195, 200, 215, 229, 240, 207, 205, 208, 185, 190, 170, 208, 225, 190, 225, 185, 180, 165, 240, 220, 212, 163, 215, 175, 205, 210, 205, 208, 215, 180, 200, 230, 211, 230, 190, 220, 180, 205, 190, 180, 205, 190, 195]

$$\mathrm{BMI} = \frac{\mathrm{weight (kg)}}{\mathrm{height (m)}^2}$$

In [48]:
# Create a numpy array from height: np_height=

# Convert np_height from inches to meter by multiplying 0.0254: np_height_m=

# Create a numpy array from weight: np_weight=

# Convert np_weight from pounds to kg by multiplying 0.453592: np_weight_kg=

# Calculate the BMI: bmi=
 
# create light array:light=bmi<21

# Print out BMIs of all baseball players whose BMI is below 21

In [49]:
np_height=np.array(height)
np_weight = np.array(weight)
np_height_m=np_height*0.0254
np_weight_kg=np_weight*0.453592
bmi=np_weight_kg/np_height_m**2
light = bmi<21
bmi[light]

array([20.54255679, 20.54255679, 20.69282047, 20.69282047, 20.34343189,
       20.34343189, 20.69282047, 20.15883472, 19.4984471 , 20.69282047,
       20.9205219 ])

**Assignment 2**  
Define your own function to calculate the  circumference  
Notice: you need to use pi form math package and keep two decimals for the result

References:
* https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
* http://cs231n.github.io/python-numpy-tutorial/#numpy